### ISSUE TITLE
Error: the file secrets.json must be populated with your api key.

### ISSUE THREAD

**Issue by kalyanks0611** [james-natale/umls_api#1]
* umls-api version: 0.1.0
* Python version: 3.6.3
* Operating System: Windows 10

 Firstly, thanks for creating a python wrapper for UMLS-API. 
I got this error  when I run the line   **from umls_api import umls_api**

**Error:** 
the file secrets.json must be populated with your api key.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-59ed25e7fdb3> in <module>()
----> 1 from umls_api import umls_api

C:\ProgramData\Anaconda3\lib\site-packages\umls_api\umls_api.py in <module>()
      6 
      7 ##get at ticket granting ticket for the session
----> 8 AuthClient = Authentication()
      9 tgt = AuthClient.gettgt()
     10 uri = "https://uts-ws.nlm.nih.gov"

C:\ProgramData\Anaconda3\lib\site-packages\umls_api\auth.py in __init__(self)
      8     def __init__(self):
      9         try:
---> 10             with open('connect.json') as f:
     11                 data = json.load(f)
     12         except:

FileNotFoundError: [Errno 2] No such file or directory: 'connect.json'

In this link https://james-natale.github.io/umls-api-githubpages/ ,  it is given that
There are two methods for passing through your apikey.

- One is via the secrets.json file in the top-level directory of the repo.
- The second is via the keyword arguments of the individual queries. To see an example of each, see the code snippets on the right.

Where I have to save the secrets.json file which is populated with api key?   I didn't find any keywords  to send the api key.  It would be so helpful if you can provide the information. Thanks in advance

**Comment by james-natale** [comment]
@kalyanks0611 I had made an update to they way you can pass the API key through to the package, but had not updated the documentation.  You can now pass your key by setting an os environment variable `UMLS_API_KEY`.

**Comment by kalyanks0611** [comment]
Thanks @james-natale .
